### ISSUE TITLE
Windows8Advertising On clicked does not Trigger

### ISSUE THREAD

**Issue by DoubleSmith** [atxryan/Windows-8-Advertising-Scirra-Plugin#5]
On clicked does not trigger, if you click or touch an advertising banner.

I want to pause the game(and stop the music) if you the user clicks on the advertising , but the it does not trigger the event.
Also the Construct2 default mouse events do not trigger, if the advertising is clicked.

Can this be fixed, or do you have any ideas for work arounds ? Tahank you very much !

Tested under Win8 With Construct2 R134

**Comment by atxryan** [comment]
Archiving project and closing all issues.
