### ISSUE TITLE
Getting error in Visual Studio.

### ISSUE THREAD

**Issue by kenhes** [atxryan/Windows-8-Advertising-Scirra-Plugin#6]
![capture](https://f.cloud.github.com/assets/5264886/989413/0940db92-0914-11e3-9b80-8d93e061af55.JPG)

I'm having an issue with it in Construct 2 release 139. I'm enabling and disabling the ads inside an in app purchase. Would this cause the error I'm getting in the image?

**Comment by atxryan** [comment]
Archiving this project and closing all issues.
